version: 0.2

phases: 
  install:
    commands:        
      - sudo yum groupinstall 'Development Tools' -y      
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" -y
      - echo >> /root/.bashrc
      - echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /root/.bashrc
      - eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"      
      #- brew doctor
  pre_build:
    commands:
      - node -v && npm -v 
      # 1. configure node version       
      # 1.1 install last node version with brew:
      - brew install node 
      - node -v && npm -v 
      #- brew install node@NN -> specific version 
      # 1.2 or last version directly from source
      #- curl -sL https://rpm.nodesource.com/setup_23.x | sudo -E bash -
      #- sudo yum install -y nodejs
      - brew unlink node && brew link node@23
      - node -v && npm -v
#      
#     - echo Installing source NPM dependencies...
#     - npm install 
#     - npm i next@latest     
  build:
    commands:
      - echo Build started on `date`
#      - echo Compiling the Node.js code
#      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
#artifacts:
#  files:
#    - build/**/*
#    - Scripts/**/*
#    - appspec.yml    