version: 0.2

phases: 
  install:
    commands:        
      - sudo yum groupinstall 'Development Tools' -y      
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" -y
      - echo >> /root/.bashrc
      - echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /root/.bashrc
      - eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"      
      #- brew doctor
  pre_build:
    commands:
      - node -v && npm -v 
      # 1. CONFIGURE NODE VERSION
      # 1.1. install last node version with brew:
      - brew install node #- brew install node@NN -> specific version 
      - node -v && npm -v       
      # 1.1. or last version directly from source
      #- curl -sL https://rpm.nodesource.com/setup_23.x | sudo -E bash -
      #- sudo yum install -y nodejs
      # 1.2. Downgrade node - if necessary: 
      #- brew unlink node && brew link node@19 #sample
      - node -v && npm -v      
  build:
    commands:
      - echo Build started on `date`
      # instal project dependeicies:
      - echo Installing source NPM dependencies...
      - npm install 
      - npm i next@latest     
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/**/*
#    - Scripts/**/*
#    - appspec.yml    